### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by Lizaixuan** [w4ngzhen/CefSharpResourceInterceptExample#1]
大佬你好，我想问一下如果我再次打开页面好像不会再次拦截js，因为js已经缓存在了本地，如何让本地不缓存呢？

**Comment by w4ngzhen** [comment]
js等文件的缓存问题，本质上都是浏览器对资源的缓存问题。可以先了解下浏览器对资源缓存的控制方式，例如资源过期判定等。这类判定通常会和HTTP响应Header里面的字段有关（Last-Modified等，还有一些），建议先系统了解下这块。
